### ISSUE TITLE
How to use ‘Plot the congestion window graph using gnuplotScriptCwnd and cwnd.plotme’？

### ISSUE THREAD

**Issue by zhuoyuechen** [mohittahiliani/BBR-Validation#1]
hello！I want to use the plotScript to plot the throughput, but I don't know how to use. I try to use gnuplot, and load the script, but the script should locate in the same directory with the 'throughput.dat'. I want to know how you use the script, Thank you!

**Comment by mohittahiliani** [comment]
Hi @zhuoyuechen - the following lines should help you to generate the plots.

https://gitlab.com/nsnam/ns-3-dev/-/blob/master/examples/tcp/tcp-bbr-example.cc#L221-L231
